---
title: Vanishing Vitamin
---


Welcome to Vanishing Vitamin! We are a group of researchers interested in thiamine (vitamin B~1~) deficiency in salmon and trout. Our working group, co-funded by the National Center for Ecological Analysis and Synthesis ([NCEAS](https://www.nceas.ucsb.edu/)) and [US Geological Survey's John Wesley Powell Center for Analysis and Synthesis,](https://www.usgs.gov/centers/john-wesley-powell-center-for-analysis-and-synthesis) is exploring the mystery of why thiamine deficiency seems to be increasing.

Thiamine Deficiency Complex (TDC) is a global threat to the stability and persistence of wildlife populations. TDC generally manifests as partial or complete reproductive failure due to low body thiamine concentrations in early life stages. Despite substantial research efforts over the past three decades, the ultimate drivers leading to TDC remain unknown to science. TDC research has historically been focused on a fisheries management approach with the goal of developing treatments for TDC to mitigate TDC-related fisheries losses. These efforts have identified parental consumption of forage fish with thiamine degrading enzymes as the leading causes of TDC. Recently, evidence has emerged that aquatic ecosystem-level shifts in the microbial production of thiamine at the base of the food web may be an important driver of observed incidences of TDC.

We are an international team of TDC experts with specialties ranging from microbiology to ocean fisheries leveraging the expert knowledge of our team and three decades of research to finally connect the dots and elucidate the causes of TDC in fishes, which will guide the direction of the next generation of TDC research.

## Project Collaborators

-   Freya Rowland [frowland\@usgs.gov](mailto:frowland@usgs.gov){.email}

-   Chris Suffridge [suffridc\@oregonstate.edu](mailto:suffridc@oregonstate.edu){.email}

-   Jacques Rinchard [jrinchar\@brockport.edu](#0){.email}

-   David Walters [waltersd\@usgs.gov](mailto:waltersd@usgs.gov){.email}

-   Dale Honeyfield [honeyfielddale\@gmail.com](mailto:honeyfielddale@gmail.com){.email}

-   Samuel Hylander [samuel.hylander\@lnu.se](mailto:samuel.hylander@lnu.se){.email}

-   Don Tillitt [dtillitt\@usgs.gov](#0){.email}

-   Rachel Johnson [rachel.johnson\@noaa.gov](#0){.email}

-   Cliff Kraft [cek7\@cornell.edu](mailto:cek7@cornell.edu){.email}

-   Kelly Shannon [shannonk\@oregonstate.edu](mailto:shannonk@oregonstate.edu){.email}

-   Matt Futia [mttfta27\@outlook.com](mailto:mttfta27@outlook.com){.email}

-   Nate Mantua [nate.mantua\@noaa.gov](mailto:nate.mantua@noaa.gov){.email}

-   Vittoria Todisco [vittoriatodisco30\@gmail.com](mailto:vittoriatodisco30@gmail.com)

-   Marc Hauber [marc.hauber\@lnu.se](mailto:marc.hauber@lnu.se){.email}

-   Miles Daniels [miles.daniels\@noaa.gov](#0){.email}

-   Caroline Ek [caroline.ek\@slu.se](#0){.email}

-   Elin Dahlgren [elin.dahlgren\@slu.se](mailto:elin.dahlgren@slu.se){.email}

-   Jenni Prokkola [jenni.prokkola\@luke.fi](mailto:jenni.prokkola@luke.fi){.email}

-   Katie Howard [kathrine.howard\@noaa.gov](mailto:kathrine.howard@noaa.gov){.email}

-   Abbie Ward [abeward\@ucsc.edu](mailto:abeward@ucsc.edu)

-   Peggy Harte [mharte\@ucdavis.edu](mailto:mharte@ucdavis.edu)

-   Becca VanArnam [rlvanarnam\@ucdavis.edu](mailto:rlvanarnam@ucdavis.edu)

-   Joe Zemmels (app developer) [jzemmels\@usgs.gov](jzemmels@usgs.gov)
